[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
docs = [
    "Sphinx == 4.5.0",
    "sphinx-book-theme == 0.3.3",
    "sphinx_copybutton == 0.5.0",
    "sphinx-tabs == 3.4.0",
]

